#!/usr/bin/env python3.4
import brlapi
from subprocess import Popen, PIPE
from re import findall

def	batinfo():
        key = 0
        acpi = Popen("acpi",stdout = PIPE, stderr = PIPE,shell = True)
        batteryInfo = str(acpi.stdout.read())
        if len(acpi.stderr.read())>3:
                batteryInfo = 'Erreur : acpi non trouvé. Veuillez l\'installer pour utiliser ce script.'
        else:
                batteryInfo = batteryInfo.replace('b\'','')
                batteryInfo = batteryInfo.replace('\\n\'','')
                if len(findall('Battery',batteryInfo))==1:
                        batteryInfo=batteryInfo.replace('Battery 0: ','')
                translate_fr={
			'remaining':'restant',
			'Charging':'En charge',
			'until charged':'avant charge complète',
			'Full':'Complète',
			'will never fully charge':'ne jamais la charger complètement',
			'Battery':'Batterie',
			'Unknown':'Inconnu',
			'Discharging':'Sur batterie'
		}
                for i in translate_fr:
                        batteryInfo=batteryInfo.replace(i, translate_fr[i])
                try:
                        b = brlapi.Connection()
                        b.enterTtyMode()
                        b.writeText(batteryInfo)
                        key = b.readKey()
                finally:
                        return key

def     main():
        batinfo()

main()
