#!/usr/bin/env python3.4
import brlapi
import sys
#sys.path[:0] = ['../../']
from mylibbraille.brl_print import *
import os
help = open("./help", 'r')
help = help.read()
i = 0
while 42:
    brl_print(help , i)
    time.sleep(3)
    i += 1
