#!/usr/bin/python3
import os
import brlapi
import sys
import time
from mylib.manage_event import *
from mylib.braille import *


def main():
    init_event()
    while 42:
        printb("Ajouter  Consulter  Réinitialiser      X", 0)
        key = get_key()
        if key == 97:
            add_event()
        elif key == 99:
            event_manager()
        elif key == 114:
            reset_event()
        elif key == 120 or key == 536936487:
            exit(0)
main()
